spring:
  datasource:
    url: jdbc:mysql://roundhouse.proxy.rlwy.net:36350/railway
    username: root
    password: zLIAUMJLQvYKrMOypuoMAsBoFgfSRbie
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 5000
