spring:
  datasource:
    url: jdbc:mysql://viaduct.proxy.rlwy.net:52566/railway
    username: root
    password: wDUJDKMbFGtgnoJlyBunspDFufuJWNyj
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 5000
